name: BetterTntRun
version: 1.0.0
main: com.bettertntrun.BetterTntRun
api-version: '1.21'
commands:
  tntrun:
    description: Commandes du TNT Run
    usage: /tntrun help
permissions:
  bettertntrun.admin:
    description: Permission admin TNTRun
    default: op
